version: '3.7'
services:
  proxy:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: westkite1201@gmail.com
      # variable names are space-separated
      ENVSUBST_VARS: FQDN
      FQDN: www.hangang.site
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/:/opt/app
      - /opt/app/node_modules
    environment:
      - NEXT_PUBLIC_NODE_ENV=production
      - NEXT_PUBLIC_UNSPLASH_ACCESS_KEY=<INSERT_YOUR_KEY>
      - NEXT_PUBLIC_GA_APP_ID=<INSERT_YOUR_KEY>
    ports:
      - '3000:3000'
    networks:
      - backend
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes: # container -> local로 mount할 수 있습니다.
      - /usr/local/var/mongodb:/data/db # container 내부에서의 경로
    ports:
      - '27017:27017'
    networks:
      - backend
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back/:/opt/app
      - /opt/app/node_modules
    environment:
      - NODE_PATH=src
      - PORT=3031
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
      - SEOUL_OPENAPI_URL=http://openapi.seoul.go.kr:8088
      - API_KEY=<INSERT_YOUR_KEY>
      - MONGODB_URI=<INSERT_YOUR_KEY>
      - KAKAO_NATIVE_APP_KEY=<INSERT_YOUR_KEY>
      - KAKAO_REST_API_KEY=<INSERT_YOUR_KEY>
      - KAKAO_JAVASCRIPT_KEY=<INSERT_YOUR_KEY>
      - KAKAO_ADMIN_KEY=<INSERT_YOUR_KEY>
      - JWT_SECRET=<INSERT_YOUR_KEY>
      - DATA_GO_API_KEY=<INSERT_YOUR_KEY>
    networks:
      - backend
    depends_on:
      - mongo
    ports:
      - '3031:3031'
networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  letsencrypt:
